#!/usr/bin/env bash
# meta: name=summary
# meta: desc=what ran, what changed and the exact next steps
# meta: profiles=minimal,devops,full,ci
# meta: os=any
# meta: needs=
# meta: root=no
#
# The last module in every profile, and the only one whose entire job is output.
#
# It works because `lib/run.sh`'s `changed` and `lib/registry.sh`'s
# `summary_record` both append to files under $DEVENV_RUNDIR, and $DEVENV_RUNDIR
# is exported into every child module. This module is a child like any other, so
# it sees every row its siblings wrote.
#
# Two consequences, both deliberate:
#
#   * its OWN row is not in the table it prints — bin/devenv records that after
#     this process exits. There is nothing to say about a module that only
#     prints, so nothing is lost.
#   * it ALWAYS exits 0, even when a sibling failed. The run's exit status is
#     bin/devenv's job (it returns the last failing module's status); a summary
#     that failed because it had bad news to report would add a second, wrong
#     failure to the very table it just printed.
#
# When `summary` is not in the plan, bin/devenv calls summary_print itself, so
# the output is identical either way and never appears twice.
set -euo pipefail
source "${DEVENV_HOME:?}/lib/common.sh"

# refresh_completions
#   The completion cache is generated by modules/10-shell.sh, which runs TENTH —
#   before lang-go installs go-blueprint, crane and golangci-lint, and before
#   cloud installs gh and glab. So the first run on a fresh box cached only the
#   tools that happened to exist by module 10, and the SECOND run cached the
#   rest: a run that changed the box after the box was supposedly converged.
#
#   This is the right place to close that: `summary` is last in every profile
#   that installs anything, so by now every tool that has a completion is on
#   disk. It stays in 10-shell.sh as well, so `devenv --only shell` is still
#   useful on its own; running it twice costs nothing, because the generator
#   goes through write_if_changed and a byte-identical cache is not rewritten.
#
#   Never fatal, and silent when there is nothing to add.
refresh_completions() {
  [ -x "$DEVENV_HOME/bin/devenv-completions" ] || return 0
  "$DEVENV_HOME/bin/devenv-completions" >/dev/null 2>&1 \
    || log_debug "the completion cache could not be refreshed"
  return 0
}

module_main() {
  refresh_completions

  # Returns 1 when a sibling module failed; that is bin/devenv's business, not
  # this module's exit status. See the header.
  summary_print || true
  return 0
}

module_main "$@"
