#!/usr/bin/env bash

# __ __|                              ___|                    _)
#    |  __ `__ \   |   | \ \  /     \___ \    _ \   __|   __|  |   _ \   __ \    __|
#    |  |   |   |  |   |  `  <            |   __/ \__ \ \__ \  |  (   |  |   | \__ \
#   _| _|  _|  _| \__,_|  _/\_\     _____/  \___| ____/ ____/ _| \___/  _|  _| ____/
#
####################################################################################
# Save the windows, panes, layouts, working directories and running commands of all
# tmux sessions into a self-contained restore script.
#
# Usage:
#   ./tmux-save-session.sh
#
# Environment:
#   SAVE_NUMERIC=1    also save auto-named sessions ("0", "1", "34", ...). Off by
#                     default: those are throwaway `tmux`-without-a-name sessions
#                     and they reappear as empty sessions on every restore.
#   EXCLUDE_RE=<ere>  extra extended-regex of session names to skip
#   OUT_DIR=<path>    where to write the restore script (default: script directory)

set -uo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
OUT_DIR=${OUT_DIR:-$SCRIPT_DIR}
SAVE_NUMERIC=${SAVE_NUMERIC:-0}
EXCLUDE_RE=${EXCLUDE_RE:-}

filename=""
saved_sessions=()
skipped_sessions=()

##############################################################################
# helpers
##############################################################################

# Quote a string as a single-quoted shell word (readable, unlike printf %q).
sq() {
  local s=${1//\'/\'\\\'\'}
  printf "'%s'" "$s"
}

# Quote a single argv element, but only when it actually needs it, so the
# generated file stays readable.
sq_arg() {
  case $1 in
    '' | *[!A-Za-z0-9_.,:=@%+/^-]*) sq "$1" ;;
    *) printf '%s' "$1" ;;
  esac
}

# Rebuild a shell-safe command line from a process' real argv.
#
# `ps -o args=` joins argv with spaces, which silently destroys quoting:
# `python3 -c "import time; sleep(1)"` comes back as two shell commands split on
# the `;`. Re-quoting each argv element from /proc keeps the command meaning the
# same thing when it is sent back to a shell.
proc_cmdline() {
  local pid=$1 arg out=""
  [ -r "/proc/$pid/cmdline" ] || return 1
  while IFS= read -r -d '' arg; do
    [ -n "$out" ] && out+=" "
    out+=$(sq_arg "$arg")
  done <"/proc/$pid/cmdline"
  [ -n "$out" ] || return 1
  printf '%s' "$out"
}

# Is this command line just an idle interactive shell?
is_shell() {
  local w=${1%% *}
  w=${w##*/}
  w=${w#-}
  case "$w" in
    bash | sh | zsh | fish | dash | ksh | csh | tcsh) return 0 ;;
  esac
  return 1
}

# Print the command running in the foreground of a pane, or nothing if the pane
# is sitting at an idle shell prompt.
#
# tpgid of the pane's shell is the foreground process group of the pane's tty,
# i.e. exactly what the user is looking at. If it points back at the shell
# itself, no command is running. This beats walking pgrep children, which picks
# up LSP servers and other background helpers spawned by editors.
pane_command() {
  local pane_pid=$1 tpgid cmd
  tpgid=$(command ps -o tpgid= -p "$pane_pid" 2>/dev/null | tr -d '[:space:]')
  [ -n "$tpgid" ] && [ "$tpgid" != "-1" ] || return 0

  cmd=$(proc_cmdline "$tpgid") || cmd=$(command ps -o args= -p "$tpgid" 2>/dev/null)
  cmd=${cmd#"${cmd%%[![:space:]]*}"}
  cmd=${cmd%"${cmd##*[![:space:]]}"}
  [ -n "$cmd" ] || return 0

  # Pane at a bare prompt: nothing worth restoring.
  if [ "$tpgid" = "$pane_pid" ] && is_shell "$cmd"; then
    return 0
  fi
  printf '%s' "$cmd"
}

skip_session() {
  local s=$1
  [ "$SAVE_NUMERIC" = 1 ] || [[ ! $s =~ ^[0-9]+$ ]] || return 0
  [ -z "$EXCLUDE_RE" ] || [[ ! $s =~ $EXCLUDE_RE ]] || return 0
  return 1
}

##############################################################################
# restore-script preamble
##############################################################################

write_preamble() {
  cat >"$filename" <<'PREAMBLE'
#!/usr/bin/env bash
#
# Restore tmux sessions.  Generated by tmux-save-session.sh -- do not hand-edit
# unless you mean it; regenerate instead.
#
#   ./this-script.sh              restore everything, run the saved commands,
#                                 attach if launched from a terminal
#   DRY_RUN=1   ./this-script.sh  type the saved commands into each pane but do
#                                 not press Enter -- review before running
#   NO_ATTACH=1 ./this-script.sh  restore only, never attach
#   SIZE=250x70 ./this-script.sh  geometry used while panes are being created
#
# Sessions that already exist are left untouched, so this is safe to re-run to
# bring back only the sessions you are missing.

set -uo pipefail

DRY_RUN=${DRY_RUN:-0}
NO_ATTACH=${NO_ATTACH:-0}
SIZE=${SIZE:-250x70}

# Commands matched here are typed into the pane but NOT executed, so nothing
# blocks on a password prompt or fires off something destructive unattended.
MANUAL_RE=${MANUAL_RE:-'^(sudo|su|doas)([[:space:]]|$)'}

command -v tmux >/dev/null 2>&1 || { echo "tmux not found in PATH" >&2; exit 1; }

tmux start-server

WIDTH=${SIZE%x*}
HEIGHT=${SIZE#*x}

WID=""      # window id of the window currently being built
P=()        # pane ids of the window currently being built
CREATED=0
SKIPPED=0
WARNINGS=0

warn() { printf '  ! %s\n' "$*" >&2; WARNINGS=$((WARNINGS + 1)); }

# Saved directories go stale (deleted repos, unmounted disks); fall back to
# $HOME instead of letting tmux refuse to create the pane.
_dir() {
  if [ -d "$1" ]; then printf '%s' "$1"; else printf '%s' "$HOME"; fi
}

session_exists() { tmux has-session -t "=$1" 2>/dev/null; }

# new_session <session> <window_index> <window_name> <cwd>
new_session() {
  local s=$1 idx=$2 name=$3 dir cur
  dir=$(_dir "$4")
  P=()
  WID=$(tmux new-session -d -s "$s" -n "$name" -c "$dir" \
          -x "$WIDTH" -y "$HEIGHT" -P -F '#{window_id}' 2>/dev/null)
  if [ -z "$WID" ]; then
    warn "could not create session '$s'"
    return 1
  fi
  # new-session always lands on base-index; move it to the index we saved.
  cur=$(tmux display-message -p -t "$WID" '#{window_index}' 2>/dev/null)
  if [ -n "$cur" ] && [ "$cur" != "$idx" ]; then
    tmux move-window -s "$WID" -t "$s:$idx" 2>/dev/null \
      || warn "$s: could not place first window at index $idx (left at $cur)"
  fi
}

# new_window <session> <window_index> <window_name> <cwd>
new_window() {
  local s=$1 idx=$2 name=$3 dir
  dir=$(_dir "$4")
  P=()
  WID=$(tmux new-window -d -t "$s:$idx" -n "$name" -c "$dir" \
          -P -F '#{window_id}' 2>/dev/null)
  if [ -z "$WID" ]; then
    # index taken (or otherwise unusable) -- append instead of losing the window
    WID=$(tmux new-window -d -t "$s:" -n "$name" -c "$dir" \
            -P -F '#{window_id}' 2>/dev/null)
    [ -n "$WID" ] && warn "$s: window index $idx unavailable, appended '$name'"
  fi
  [ -n "$WID" ] || warn "$s: could not create window '$name'"
}

pane_first() {
  [ -n "$WID" ] || return 0
  P+=("$(tmux list-panes -t "$WID" -F '#{pane_id}' 2>/dev/null | head -1)")
}

# pane_split <cwd>
pane_split() {
  local dir pid
  [ -n "$WID" ] || return 0
  dir=$(_dir "$1")
  pid=$(tmux split-window -t "$WID" -c "$dir" -P -F '#{pane_id}' 2>/dev/null)
  [ -n "$pid" ] || warn "no room to split window $(tmux display-message -p -t "$WID" '#{session_name}:#{window_name}' 2>/dev/null)"
  P+=("$pid")
}

# apply_layout <layout-string> -- once per window, after every pane exists
apply_layout() {
  [ -n "$WID" ] || return 0
  tmux select-layout -t "$WID" "$1" >/dev/null 2>&1
}

# run_in <pane-slot> <command>
run_in() {
  local pane=${P[$1]:-} cmd=$2
  [ -n "$pane" ] && [ -n "$cmd" ] || return 0
  if [ "$DRY_RUN" = 1 ] || [[ $cmd =~ $MANUAL_RE ]]; then
    # typed, not executed -- the pane waits for you to hit Enter
    tmux send-keys -t "$pane" "$cmd"
  else
    tmux send-keys -t "$pane" "$cmd" Enter
  fi
}

begin_session() {
  if session_exists "$1"; then
    printf '  = %s (already running, left alone)\n' "$1"
    SKIPPED=$((SKIPPED + 1))
    return 1
  fi
  printf '  + %s\n' "$1"
  CREATED=$((CREATED + 1))
  return 0
}

echo "Restoring tmux sessions..."

PREAMBLE
}

write_epilogue() {
  cat >>"$filename" <<'EPILOGUE'

printf '\nRestored %d session(s), skipped %d already running' "$CREATED" "$SKIPPED"
[ "$WARNINGS" -gt 0 ] && printf ', %d warning(s)' "$WARNINGS"
printf '.\n'

if [ "$NO_ATTACH" = 1 ] || [ -n "${TMUX:-}" ] || [ ! -t 0 ] || [ ! -t 1 ]; then
  echo "Attach with: tmux attach"
  exit 0
fi

target=$(tmux list-sessions -F '#{session_name}' 2>/dev/null | head -1)
[ -n "$target" ] && exec tmux attach-session -t "=$target"
exit 0
EPILOGUE
}

##############################################################################
# session capture
##############################################################################

save_sessions() {
  local fmt
  local s widx wname layout pidx ppid cwd
  local cur_session="" cur_window="" pending_layout="" slot=0
  local -a cmds=()
  local skipping=0

  fmt=$'#{session_name}\t#{window_index}\t#{window_name}\t#{window_layout}\t#{pane_index}\t#{pane_pid}\t#{pane_current_path}'

  flush_window() {
    local i
    [ -n "$cur_window" ] || return 0
    [ "$skipping" = 1 ] && return 0
    printf '  apply_layout %s\n' "$(sq "$pending_layout")" >>"$filename"
    for i in "${!cmds[@]}"; do
      [ -n "${cmds[$i]}" ] || continue
      printf '  run_in %d %s\n' "$i" "$(sq "${cmds[$i]}")" >>"$filename"
    done
    cmds=()
  }

  end_session() {
    [ -n "$cur_session" ] || return 0
    [ "$skipping" = 1 ] && return 0
    printf 'fi\n' >>"$filename"
  }

  # shellcheck disable=SC2034  # pidx is a positional placeholder: the field is read and not used
  while IFS=$'\t' read -r s widx wname layout pidx ppid cwd; do
    [ -n "$s" ] || continue

    if [ "$s" != "$cur_session" ]; then
      flush_window
      end_session
      cur_window=""
      cur_session=$s

      if skip_session "$s"; then
        skipping=1
        skipped_sessions+=("$s")
        continue
      fi
      skipping=0
      saved_sessions+=("$s")

      # `tmux list-panes -a` walks sessions in name order, so every session's
      # rows are contiguous. If that ever stops holding we would emit a second
      # block for the same session and silently drop its later windows.
      if [ -n "${session_seen[$s]:-}" ]; then
        echo "WARNING: session '$s' appeared twice in tmux output; later windows may be lost" >&2
      fi
      session_seen[$s]=1

      {
        printf '\n'
        printf '# %s\n' "$(printf '%.0s-' {1..72})"
        printf '# session: %s\n' "$s"
        printf '# %s\n' "$(printf '%.0s-' {1..72})"
        printf 'S=%s\n' "$(sq "$s")"
        # shellcheck disable=SC2016  # $S is written literally into the generated script
        printf 'if begin_session "$S"; then\n'
      } >>"$filename"
    fi

    [ "$skipping" = 1 ] && continue

    if [ "$s:$widx" != "$cur_window" ]; then
      flush_window
      cur_window="$s:$widx"
      pending_layout=$layout
      slot=0
      cmds=()

      printf '\n  # window %s: %s\n' "$widx" "$wname" >>"$filename"
      if [ -z "${window_seen[$s]:-}" ]; then
        window_seen[$s]=1
        # shellcheck disable=SC2016  # ditto: $S is the generated script's own variable
        printf '  new_session "$S" %s %s %s\n' \
          "$widx" "$(sq "$wname")" "$(sq "$cwd")" >>"$filename"
      else
        # shellcheck disable=SC2016  # ditto
        printf '  new_window "$S" %s %s %s\n' \
          "$widx" "$(sq "$wname")" "$(sq "$cwd")" >>"$filename"
      fi
      printf '  pane_first\n' >>"$filename"
    else
      printf '  pane_split %s\n' "$(sq "$cwd")" >>"$filename"
    fi

    cmds[slot]=$(pane_command "$ppid")
    slot=$((slot + 1))
  done < <(tmux list-panes -a -F "$fmt" 2>/dev/null)

  flush_window
  end_session
  return 0
}

##############################################################################
# README
##############################################################################

update_readme() {
  local readme_file="$OUT_DIR/README.md"
  local current_date session window_count pane_count session_file file_date status
  local total_sessions=0 total_windows=0 total_panes=0
  current_date=$(date "+%Y-%m-%d %H:%M:%S")

  {
    echo "# Tmux Sessions Backup"
    echo ""
    echo "Generated on: $current_date"
    echo ""
    echo "## Latest Session: $(basename "$filename" .sh)"
    echo ""
    echo "### Sessions Overview"
    echo ""
    echo "| Session Name | Windows | Total Panes | Status |"
    echo "|-------------|---------|-------------|--------|"
  } >"$readme_file"

  for session in "${saved_sessions[@]}"; do
    window_count=$(tmux list-windows -t "=$session" 2>/dev/null | wc -l)
    pane_count=$(tmux list-panes -s -t "=$session" 2>/dev/null | wc -l)
    total_sessions=$((total_sessions + 1))
    total_windows=$((total_windows + window_count))
    total_panes=$((total_panes + pane_count))
    echo "| $session | $window_count | $pane_count | ✅ Saved |" >>"$readme_file"
  done

  for session in "${skipped_sessions[@]}"; do
    window_count=$(tmux list-windows -t "=$session" 2>/dev/null | wc -l)
    pane_count=$(tmux list-panes -s -t "=$session" 2>/dev/null | wc -l)
    echo "| $session | $window_count | $pane_count | ⏭️ Skipped (unnamed) |" >>"$readme_file"
  done

  {
    echo ""
    echo "**Totals:** $total_sessions sessions, $total_windows windows, $total_panes panes"
    echo ""
    echo "### Detailed Session Breakdown"
    echo ""
  } >>"$readme_file"

  for session in $( ((${#saved_sessions[@]})) && printf '%s\n' "${saved_sessions[@]}" | sort); do
    {
      echo "#### Session: \`$session\`"
      echo ""
      echo "| Window | Name | Panes | Layout | Directory |"
      echo "|--------|------|-------|--------|-----------|"
    } >>"$readme_file"

    tmux list-windows -t "=$session" \
      -F $'#{window_index}\t#{window_name}\t#{window_panes}\t#{window_layout}\t#{pane_current_path}' 2>/dev/null \
      | while IFS=$'\t' read -r window_index window_name window_panes layout current_path; do
        echo "| $window_index | $window_name | $window_panes | \`${layout:0:20}...\` | \`${current_path/#$HOME/\~}\` |" >>"$readme_file"
      done

    echo "" >>"$readme_file"
  done

  {
    echo "### Available Session Files"
    echo ""
    echo "| File | Date Created | Status |"
    echo "|------|--------------|--------|"
  } >>"$readme_file"

  # shellcheck disable=SC2012  # newest-first is the point; find cannot sort by mtime
  while IFS= read -r session_file; do
    [ -f "$OUT_DIR/$session_file" ] || continue
    file_date=$(date -r "$OUT_DIR/$session_file" "+%Y-%m-%d" 2>/dev/null)
    status="📁 Available"
    [ "$session_file" = "$(basename "$filename")" ] && status="⭐ Latest"
    echo "| \`$session_file\` | $file_date | $status |" >>"$readme_file"
  done < <(cd "$OUT_DIR" && ls -t sessions-*.sh 2>/dev/null | head -20)

  {
    echo ""
    echo "### Usage"
    echo ""
    echo "Save the current sessions:"
    echo ""
    echo '```bash'
    echo "./tmux-save-session.sh"
    echo '```'
    echo ""
    echo "Restore them later:"
    echo ""
    echo '```bash'
    echo "./$(basename "$filename")            # restore + run saved commands + attach"
    echo "DRY_RUN=1 ./$(basename "$filename")  # type commands into the panes, do not run them"
    echo "NO_ATTACH=1 ./$(basename "$filename")"
    echo '```'
    echo ""
    echo "Restoring is idempotent: sessions that already exist are left alone, so"
    echo "re-running only brings back the ones you are missing."
    echo ""
    echo "Auto-named sessions (\`tmux\` started without \`-s <name>\`, which tmux calls"
    echo "\`0\`, \`1\`, ...) are not saved -- they used to come back as empty sessions on"
    echo "every restore. Set \`SAVE_NUMERIC=1\` when saving if you want them."
  } >>"$readme_file"

  echo "README updated: $readme_file"
}

##############################################################################
# main
##############################################################################

declare -A window_seen=()
declare -A session_seen=()

main() {
  if ! tmux has-session 2>/dev/null; then
    echo "No tmux sessions exist, exiting." >&2
    exit 1
  fi

  local timestamp
  timestamp=$(date "+%s")
  filename="$OUT_DIR/sessions-$(date "+%F")-${timestamp:6}.sh"

  echo "Saving tmux sessions to: $filename"
  write_preamble
  save_sessions
  write_epilogue
  chmod +x "$filename"

  if ! bash -n "$filename"; then
    echo "Generated script has a syntax error, not overwriting README." >&2
    exit 1
  fi

  echo "Saved sessions (${#saved_sessions[@]}): ${saved_sessions[*]}"
  if [ "${#skipped_sessions[@]}" -gt 0 ]; then
    echo "Skipped unnamed sessions (${#skipped_sessions[@]}): ${skipped_sessions[*]}"
    echo "  (set SAVE_NUMERIC=1 to include them)"
  fi
  echo "Backup saved to: $filename"

  update_readme
}

main "$@"
